
services:
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=product_service_db
volumes:
  pgdata: